### ISSUE TITLE
Where is iso file?

### ISSUE THREAD

**Issue by joelhickok** [t2linux/fedora-iso#11]
I'm sorry, maybe I am confused.  I do not see the iso whole or in parts to download anywhere in the repo.  Or links to find it.  Where is the iso currently located?  Thank you!

**Comment by sharpenedblade** [comment]
The first ISO file is for workstation(gnome), the two files with numbers at the end are for KDE, you need to combine them together.

**Comment by joelhickok** [comment]
Sorry, I didn't realize they are all under Releases.

**Comment by joelhickok** [comment]
Does KDE have better compatibility, or does it not matter since they use the same kernel?

**Comment by sharpenedblade** [comment]
It doesnt matter, pick whatever you are more comfortable with.
