### ISSUE TITLE
Touchbar script throws error when switching modes

### ISSUE THREAD

**Issue by sharpenedblade** [t2linux/fedora-iso#4]
# Steps to reproduce
1. Run `sudo touchbar`
2. Select a touchbar mode (media or fn keys)

# What should happen
The touchbar uses the selected mode

# What actually happens
It will crash with the error: `/sys/class/input/*/device/fnmode directory not found.`

**Comment by parm02** [comment]
Enabling igpu fixes this https://github.com/t2linux/fedora-iso/issues/3

**Comment by sharpenedblade** [comment]
It was probably because of an kernel update or intermittent problem, but since it works im closing this.
