### ISSUE TITLE
ISO doesn't boot on MBAir 2018

### ISSUE THREAD

**Issue by eliobtl** [t2linux/fedora-iso#9]
Hi,

I tried to install fedora KDE on a macbook air 2018, following the guide on [wiki.t2linux.org](wiki.t2linux.org) : 
- I grabed firmware files and put them on the EFI partition using the provided script
- I disabled secure boot and allowed booting from external devices
- I tried to install debian, but wifi drivers support was not good, so I decided to try fedora because of the pre-built ISO
- I downloaded the two KDE isos and merged them with `cat`
- I put the ISO on a usb stick with `dd`
- I tried to boot the ISO (using the alt key)

But the usb stick does not appear in the menu, in fact, nothing appears but the internet recovery

If anyone has an idea on why this happens, thanks for your help

**Comment by AntonyThorpe** [comment]
I got the same error.  I downloaded the two KDE ISOs again & repeated the steps.  It worked :).
